# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/jun1996ar/f333e1b3fe925458a1d191cae42b3ed1/data.ipynb
"""

import pandas as pd

housing= pd.read_csv("/content/sample_data/california_housing_test.csv")

housing.head()

housing.info()

json_file = pd.read_json("/content/sample_data/anscombe.json")

json_file.head()

json_file.info()

